force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Log__c.field-meta.xml
<CustomField>
    <fullName>Log__c</fullName>
    <label>Log</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Log_Details__c.field-meta.xml
<CustomField>
    <fullName>Log_Details__c</fullName>
    <label>Log Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLog.cls
/**
* The purpose of this method is to create a new record of Error_Log__c object and insert it into the database. 
* This method returns the Id of the newly created Error_Log__c record. 
*/
public with sharing class ErrorLog {
    public static Id insertErrorLog(Datetime dt,String logDetails, String processName,String errorLogName ){
        // Create a new instance of Error_Log__c object
        Error_Log__c newLogObj=new Error_Log__c();
        // Set the values of fields of the Error_Log__c object
        newLogObj.Process_Name__c=processName;
        newLogObj.Log_Details__c=logDetails;
        newLogObj.Log__c=dt;
        newLogObj.Name=errorLogName;
        // Insert the newly created record into the database
        insert newLogObj;
        // Return the Id of the newly created Error_Log__c record
        return newLogObj.Id;
    }

}