force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogTest.cls
@IsTest
public class ErrorLogTest {
    @IsTest
    private static void insertErrorLogTest(){
        test.startTest();
        DateTime dt = DateTime.now();
        id errorRecordId=ErrorLog.insertErrorLog(dt, 'ErrorDetailsTest', 'test', 'testlog');
        Error_Log__c newLog=new Error_Log__c();
        newLog=[select 	Process_Name__c from Error_Log__c where id= : errorRecordId];

        system.assertEquals('test', newLog.Process_Name__c);

        test.stopTest();
    }
}