force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Attendee</relationshipLabel>
    <relationshipName>Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeRegistrationPageExtension.cls
public class AttendeeRegistrationPageExtension {

    private ApexPages.StandardController controller;
    public Attendees__c attendee{get;set;}
    public Event_Attendee__c eventAttendee{get;set;}
    public Location_Address_Book__c	 loc{get;set;}
    // public String Event__c.Organizer__r.Address__c {get;set;}
    public AttendeeRegistrationPageExtension(ApexPages.StandardController controller) {
        this.controller = controller;
        attendee=new Attendees__c();
        eventAttendee=new Event_Attendee__c();
        loc=new Location_Address_Book__c();
        
    }

    public void s() {
        Savepoint sp=Database.setSavepoint();
        try{
            insert loc;
           attendee.Address__c=loc.id;
           insert attendee;
           eventAttendee.Attendee__c=attendee.id;
           insert eventAttendee;

        }catch(Exception e){
            System.debug(e.getMessage());
            Database.rollback(sp);
        }
        
        
    }
    
}