force-app/main/default/objects/Attendees__c/Attendees__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendees Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendee</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendees__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Attendee</relationshipLabel>
    <relationshipName>Attendee</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event-Attendee</label>
    <nameField>
        <label>Event-Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendees__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerHelper.cls
public with sharing class EventAttendeeTriggerHelper {
    // Define a virtual BaseException class and a subclass OtherException
    public virtual class BaseException extends Exception {}
    public class OtherException extends BaseException {}

    // Define a static method to send emails to Event Attendees
    public static void sendMailTOAttendee(List<Event_Attendee__c> newEventAttendeeRecords){

        // Create a list to store Event Attendee record IDs and a list to store email messages
        List<Id> eventAttendeeId=new List<Id>();
        List<Messaging.Email> emailList=new List<Messaging.Email>();

        // Loop through new Event Attendee records and add their IDs to the eventAttendeeId list
        for(Event_Attendee__c eventAttendeeObj:newEventAttendeeRecords){
            eventAttendeeId.add(eventAttendeeObj.Id);
        }
        // Use a query to retrieve Event Attendee, Attendee, Event, and Location records based on their IDs
        Map<id,Event_Attendee__c> eventAttendeeDetails=new Map<id,Event_Attendee__c>([select Attendee__r.Email__c,Attendee__r.Name,Event__r.Name__c,Event__r.Start__c,Event__r.Location__r.Name,Event__r.Organizer__r.Name from Event_Attendee__c where id in : eventAttendeeId]);
        
        
        // Loop through the retrieved records and create an email message for each Event Attendee
        for(Id recordId: eventAttendeeDetails.KeySet()){
            String email=eventAttendeeDetails.get(recordId).Attendee__r.Email__c;
            String attendeeName=eventAttendeeDetails.get(recordId).Attendee__r.Name;
            String eventName= eventAttendeeDetails.get(recordId).Event__r.Name__c;
            Datetime eventDate=eventAttendeeDetails.get(recordId).Event__r.Start__c;
            String eventLocation=eventAttendeeDetails.get(recordId).Event__r.Location__r.Name;
            String eventOrganizer=eventAttendeeDetails.get(recordId).Event__r.Organizer__r.Name;
            
            if(email!=NULL && attendeeName!=NULL && eventName!=NULL && eventDate!=NULL && eventLocation!=NULL && eventOrganizer!=NULL){
                
                  Messaging.SingleEmailMessage emailMsg=new Messaging.SingleEmailMessage();
                  emailMsg.setToAddresses(new String[]{email});
                  String emailSubject='Pass for the '+ eventName;
                  emailMsg.setSubject(emailSubject);
                  String senderName='Ridham';
                  emailMsg.setSenderDisplayName(senderName);
                  String body='Dear ' + attendeeName+ ',<br/> Thank you for registering for '+ eventName+
                  ' which will be organized on '+ eventDate +' and will be held in ' + eventLocation+ '.We are excited to have you, see you at the event. <br/><br/> Thanks,<br/>'+eventOrganizer; 
                  emailMsg.setHtmlBody(body);
                  emailList.add(emailMsg);
              }else{
                // If any required field is null, throw OtherException with an error message
                throw new OtherException('Either Email or Attendee Name or Event Name or event date or event Location or event Organizer is NULL');
              }
         }
          // Send email messages in the emailList using the Messaging.sendEmail method
          Messaging.sendEmail(emailList);
         
    }
}