force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Max_Seats__c.field-meta.xml
<CustomField>
    <fullName>Max_Seats__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Max Seats</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event-Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Speaker__c/Speaker__c.object-meta.xml
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/EventSpeakerTriggerHelperTest.cls
@isTest
public with sharing class EventSpeakerTriggerHelperTest {
    // Test method to verify that two events cannot have the same speaker
    @isTest
    private static void twoeventclashtest(){
        // Create first event with a speaker
        Event__c event1=new Event__c();
        event1.start__c=Datetime.newInstanceGmt(2023, 4, 18, 3, 3, 3);
        event1.end__c=Datetime.newInstanceGmt(2023, 4, 25, 3, 3, 3);
        event1.live__c=true;
        event1.Max_Seats__c=20.00;
        insert event1;

        // Create a speaker
        Speaker__c speaker1=new Speaker__c();
        speaker1.Name='Ridham';
        insert speaker1;

        // Assign the speaker to the first event
        Event_Speaker__c eventSpeaker1=new Event_Speaker__c();
        eventSpeaker1.Name='Rajesh';
        eventSpeaker1.Speaker__c=speaker1.id;
        eventSpeaker1.Event__c=event1.id;

        insert eventSpeaker1;
        try{
            
            Event__c event2=new Event__c();
            event2.start__c=Datetime.newInstanceGmt(2023, 4, 20, 3, 3, 3);
            event2.end__c=Datetime.newInstanceGmt(2023, 4,27, 3, 3, 3);
            event2.live__c=true;
            event2.Max_Seats__c=20.00;
            
            insert event2;

            Event_Speaker__c eventSpeaker2=new Event_Speaker__c();
            eventSpeaker2.Name='Kamal';
            eventSpeaker2.Speaker__c=speaker1.id;
            eventSpeaker2.Event__c=event2.id;

            insert eventSpeaker2;
            
        }
        catch(Exception e){
            // Verify that the expected exception is thrown when trying to insert an event with the same speaker as the first event
            Boolean expectedExceptionThrown =  e.getMessage().contains('Duplicate Speaker found in Event-Speaker records') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }
        

        




    }

}